apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/asher-lab/jhb.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
    - selfHeal: true
    - prune: true
