apiVersion: apps/v1
kind: Deployment
metadata:
  name: siteadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siteadmin-svc
      release: siteadmin-svc-test
  template:
    metadata:
      labels:
        app: siteadmin-svc
        release: siteadmin-svc-test
    spec:
      containers:
      - name: siteadmin-container
        image: asherlab/foroforerror:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: siteadmin-svc
spec:
  selector:
    app: siteadmin-svc
    release: siteadmin-svc-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: api.asherl.com
    http:
      paths:
      - path: /v1/siteadmin(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: siteadmin-svc
            port:
              number: 80